# Generated by Django 3.2 on 2021-07-25 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(blank=True, max_length=30, verbose_name='博客名')),
                ('blogType', models.CharField(blank=True, max_length=20, verbose_name='博客类型')),
                ('blogPublishTime', models.DateTimeField(default=datetime.datetime(2021, 7, 25, 1, 23, 26, 657350, tzinfo=utc), verbose_name='博客发表时间')),
                ('blogAuthor', models.CharField(max_length=30, verbose_name='博客发表人')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
    ]
